<?php

namespace PortefolioBundle\Repository;

/**
 * outilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class outilRepository extends \Doctrine\ORM\EntityRepository
{
}
