<?php

namespace PortefolioBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function lesAutresProjets($id)
    {
        $qb=$this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id != :id')
            ->setParameter("id",$id);
        return $qb->getQuery()->getResult();
    }
}
