portefolio_homepage:
    path:     /
    defaults: { _controller: PortefolioBundle:Portfolio:index }

portefolio_aff_un_projet:
    path: /projet/{id}
    defaults: {_controller: PortefolioBundle:Portfolio:afficherUnProjet, id : 1}
    requirements:
      id: \d*
portefolio_aff_cv:
    path: /cv
    defaults: {_controller: PortefolioBundle:Portfolio:afficherCv}